name: wingmanbd
version: 0.0.1+1
publish_to: none
description: The ultimate medical support in a minimal time.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  get: 4.6.5
  super_ui_kit:
    git:
      url: https://github.com/krzshipon/super_ui_kit.git
      ref: dev
  realm: ^1.3.0
  path_provider: ^2.0.10
  water_drop_nav_bar: ^2.2.0+5

  flutter: 
    sdk: flutter
  package_info_plus: ^4.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/config/
   - assets/img/
   - assets/animations/
   - assets/locales/

